[project]
name = "snomed_post_processing"

version = "2.0.0"
description = "Program that creates SNOMED CT dumps of a particular version and/or with some filters for semantic tags or concept ids applied. It also logs SNOMED CT annotated documents under these filters in mind."
readme = "README.md"
requires-python = "~=3.9.0"
authors = [
  {name = "Franz Matthies", email = "franz.matthies@imise.uni-leipzig.de"},
]
maintainers = [
  {name = "Franz Matthies", email = "franz.matthies@imise.uni-leipzig.de"},
]
dependencies = [
    "click>=8.1.8",
    "dkpro-cassis>=0.10.1",
    "h5py>=3.14.0",
    "pandas>=2.3.3",
    "pycaprio>=0.3.0",
    "pydantic>=2.12.5",
    "pyinquirer>=1.0.3",
    "randomname>=0.2.1",
    "requests==2.27.1",
    "scttsrapy",
    "streamlit>=1.50.0",
    "yaspin>=3.3.0",
]

[dependency-groups]
dev = [
    "pytest>=8.4.0,<9",
]

[tool.uv.sources]
scttsrapy = { git = "https://github.com/AberystwythSystemsBiology/SCTTSRApy" }

[project.scripts]
log-critical-documents = "snomed_post_processing.cli.app:log_documents"
create-concepts-dump = "snomed_post_processing.cli.app:create_concept_id_dump"
summarize-hdf5 = "snomed_post_processing.cli.app:summarize_hdf5"
build-snogit-cache = "snomed_post_processing.cli.app:build_snogit_cache_cli"
suggest-sanitization = "snomed_post_processing.cli.app:suggest_sanitization_cli"
build-annotation-store = "snomed_post_processing.cli.app:build_annotation_store_cli"
check-annotation-store-document = "snomed_post_processing.cli.app:check_annotation_store_document_cli"
build-inception-shell-project = "snomed_post_processing.cli.app:build_inception_shell_project_cli"
build-inception-upload-artifacts = "snomed_post_processing.cli.app:build_inception_upload_artifacts_cli"
apply-decisions-to-inception = "snomed_post_processing.cli.app:apply_decisions_to_inception_cli"
deploy-inception-sanitized-project = "snomed_post_processing.cli.app:deploy_inception_sanitized_project_cli"
list-branches = "snomed_post_processing.cli.app:list_branches"
program-entry = "snomed_post_processing.cli.app:help_me"

[build-system]
requires = ["uv_build>=0.9.9,<0.10.0"]
build-backend = "uv_build"
